<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aban.AppInfra\Aban.AppInfra.csproj" />
    <ProjectReference Include="..\Aban.Domain\Aban.Domain.csproj" />
  </ItemGroup>

</Project>
